rtabmap:
  ros__parameters:
    # ─── Frame configuration ───
    frame_id: "base_link"
    odom_frame_id: "rtabmap/odom"
    map_frame_id: "map"

    # ─── LiDAR-only input ───
    subscribe_scan: true
    subscribe_scan_cloud: false
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_stereo: false
    subscribe_rgbd: false
    rgbd_cameras: 0

    # ─── Topics ───
    scan_topic: "/scan"
    odom_topic: "/rtabmap/odom"
    subscribe_odom_info: true

    # ─── Synchronization ───
    approx_sync: true
    queue_size: 10

    # ─── Odometry ───
    icp_odometry: true
    visual_odometry: false

    # ─── 2D occupancy grid (nested mapping!) ───
    Grid:
      Sensor:                           0      # use LaserScan
      FromDepth:                        false  # no depth-based grid
      RangeMin:                         0.12
      RangeMax:                         10.0
      CellSize:                         0.05    # now a double, not a string
      MapNegativeScansEmptyOverRayTrace: true

    # ─── Continuous map updates ───
    RGBD:
      AngularUpdate:                   0.1
      LinearUpdate:                    0.1
    map_always_update:                 true
    map_empty_ray_tracing:             true

    # ─── Memory & registration ───
    Mem:
      IncrementalMemory:               true
    Reg:
      Strategy:                        1      # ICP
      Force3DoF:                       true

    # ─── Disable visual features ───
    Rtabmap:
      ImagesAlreadySynchronized:       true
    Vis:
      MaxFeatures:                     0
